package com.example.model

import android.graphics.Bitmap

data class NutritionAnalysis(
    val foodName: String,
    val foodNameEn: String = "",
    val calories: Int,
    val protein: Float,
    val carbs: Float,
    val fat: Float,
    val fiber: Float = 0f,
    val sugar: Float = 0f,
    val sodium: Int = 0,
    val portionSize: String = "1 จาน",
    val mealType: String = "มื้อเที่ยง",
    val healthTip: String = "",
    val ingredients: List<String> = emptyList(),
    val confidence: Float = 0.95f,
    val bitmap: Bitmap? = null,
    val cuisine: String = "Thai"
)

// Preloaded Swiss, Thai & international food samples for immediate test / emulator without physical webcam
object FoodSamples {
    val swissDishes = listOf(
        NutritionAnalysis(
            foodName = "สวิสชีสฟองดูว์",
            foodNameEn = "Swiss Cheese Fondue",
            calories = 680,
            protein = 32.0f,
            carbs = 46.0f,
            fat = 38.5f,
            fiber = 2.0f,
            sugar = 2.4f,
            sodium = 940,
            portionSize = "1 ชุดพร้อมขนมปัง (250g)",
            mealType = "มื้อเย็น",
            healthTip = "แคลเซียมและโปรตีนสูงมากจากชีส Gruyère และ Emmental ควรรับประทานคู่กับชาดำอุ่นหรือไวน์ขาวสวิส และหลีกเลี่ยงน้ำเย็นจัด",
            ingredients = listOf("ชีส Gruyère AOP", "ชีส Emmental AOP", "ไวน์ขาวสวิส", "ขนมปังบาแก็ตต์หั่นเต๋า", "กระเทียม", "เหล้าเคิร์ช (Kirsch)", "ลูกจันทน์เทศ"),
            cuisine = "Swiss"
        ),
        NutritionAnalysis(
            foodName = "ราเคล็ตต์สวิส",
            foodNameEn = "Swiss Raclette",
            calories = 520,
            protein = 27.5f,
            carbs = 36.0f,
            fat = 29.0f,
            fiber = 3.2f,
            sugar = 1.8f,
            sodium = 860,
            portionSize = "1 จาน (260g)",
            mealType = "มื้อเย็น",
            healthTip = "ชีสราเคล็ตต์สวิสแท้ให้โปรตีนเข้มข้นและฟอสฟอรัสบำรุงกระดูก เสิร์ฟคู่กับมันฝรั่งต้มทั้งเปลือก (Gschwellti) และแตงกวาดองตัดเลี่ยน",
            ingredients = listOf("ชีส Raclette สวิสละลาย", "มันฝรั่งต้มทั้งเปลือก", "แตงกวาดอง (Cornichons)", "หอมดอง (Silver-skin onions)", "พริกไทยดำบดสด"),
            cuisine = "Swiss"
        ),
        NutritionAnalysis(
            foodName = "เรอสติสวิส ไข่ดาวและเบคอน",
            foodNameEn = "Swiss Rösti with Fried Egg & Bacon",
            calories = 510,
            protein = 18.0f,
            carbs = 52.0f,
            fat = 25.5f,
            fiber = 4.5f,
            sugar = 2.2f,
            sodium = 690,
            portionSize = "1 จาน (300g)",
            mealType = "มื้อเช้า",
            healthTip = "อาหารประจำชาติสวิสยอดนิยม ให้พลังงานคาร์โบไฮเดรตและโพแทสเซียมสูง เหมาะสำหรับกิจกรรมเดินเขาหรือเล่นสกีบนเทือกเขาแอลป์",
            ingredients = listOf("มันฝรั่งขูดเส้นทอดเนยสีทอง", "ไข่ดาว", "เบคอนสวิสกรอบ", "เนยสด", "เกลือหิมาลายันและพริกไทยดำ"),
            cuisine = "Swiss"
        ),
        NutritionAnalysis(
            foodName = "เนื้อลูกวัวซอสครีมเห็ดซูริก",
            foodNameEn = "Zurich-Style Veal (Zürcher Geschnetzeltes)",
            calories = 560,
            protein = 39.0f,
            carbs = 14.0f,
            fat = 36.0f,
            fiber = 2.2f,
            sugar = 3.2f,
            sodium = 760,
            portionSize = "1 จาน (310g)",
            mealType = "มื้อเที่ยง",
            healthTip = "โปรตีนบริสุทธิ์สูงและธาตุเหล็กจากเนื้อลูกวัว เห็ดแชมปิญองให้วิตามินบี ทานคู่กับเรอสติหรือสลัดผักรวม",
            ingredients = listOf("เนื้อลูกวัวหั่นเส้น", "เห็ดแชมปิญองสด", "ครีมสดสวิส (Rahm)", "ไวน์ขาวสวิส", "หอมแดงสับ", "ผักชีฝรั่งพาสลีย์"),
            cuisine = "Swiss"
        ),
        NutritionAnalysis(
            foodName = "เบอร์เชอร์ มึสลีสวิส",
            foodNameEn = "Traditional Swiss Bircher Muesli",
            calories = 310,
            protein = 12.5f,
            carbs = 50.0f,
            fat = 6.8f,
            fiber = 6.5f,
            sugar = 16.0f,
            sodium = 80,
            portionSize = "1 ถ้วย (250g)",
            mealType = "มื้อเช้า",
            healthTip = "คิดค้นโดย นพ. Bircher-Benner ในสวิตเซอร์แลนด์ ใยอาหารเบต้ากลูแคนสูง ช่วยลดคอเลสเตอรอล บำรุงระบบขับถ่ายและดีต่อสุขภาพหัวใจ",
            ingredients = listOf("ข้าวโอ๊ตแช่นมสดข้ามคืน", "แอปเปิ้ลสวิสขูดสด", "โยเกิร์ตธรรมชาติ", "ผลเบอร์รี่สดรวม", "เฮเซลนัทและอัลมอนด์อบ", "น้ำผึ้งธรรมชาติ"),
            cuisine = "Swiss"
        ),
        NutritionAnalysis(
            foodName = "แอลป์เลอร์มากาโรนี (อบชีสสไตล์แอลป์)",
            foodNameEn = "Swiss Alpine Macaroni (Älplermagronen)",
            calories = 590,
            protein = 21.0f,
            carbs = 72.0f,
            fat = 24.5f,
            fiber = 4.0f,
            sugar = 12.0f,
            sodium = 790,
            portionSize = "1 จาน (320g)",
            mealType = "มื้อเที่ยง",
            healthTip = "อาหารพื้นเมืองคนเลี้ยงวัวบนเทือกเขาแอลป์ ผสมพาสต้า มันฝรั่ง และชีสสวิส เสิร์ฟคู่กับซอสแอปเปิ้ล (Apfelmus) เพื่อตัดรสชาติ ให้พลังงานยาวนาน",
            ingredients = listOf("พาสต้ามักกะโรนี", "มันฝรั่งหั่นเต๋า", "ชีส Gruyère & Appenzeller", "ครีมสด", "หอมใหญ่เจียวคาราเมล", "ซอสแอปเปิ้ลบดสด"),
            cuisine = "Swiss"
        ),
        NutritionAnalysis(
            foodName = "ซุปข้าวบาร์เลย์สวิส กริซองส์",
            foodNameEn = "Swiss Graubünden Barley Soup",
            calories = 275,
            protein = 15.5f,
            carbs = 33.0f,
            fat = 8.0f,
            fiber = 7.0f,
            sugar = 3.8f,
            sodium = 710,
            portionSize = "1 ชาม (350ml)",
            mealType = "มื้อเย็น",
            healthTip = "ซุปอบอุ่นจากแคว้น Graubünden ข้าวบาร์เลย์อุดมด้วยใยอาหารละลายน้ำ ช่วยควบคุมระดับน้ำตาลและคอเลสเตอรอลในเลือด",
            ingredients = listOf("ข้าวบาร์เลย์มุกสวิส", "เนื้อเค็ม Bündnerfleisch หรือแฮมรมควัน", "แครอทและเซเลอรี", "กระหล่ำปลีขาว", "น้ำสต๊อกผักสมุนไพร"),
            cuisine = "Swiss"
        ),
        NutritionAnalysis(
            foodName = "ดาร์กช็อกโกแลตสวิส 70% & เฮเซลนัท",
            foodNameEn = "Swiss Dark Chocolate & Hazelnuts",
            calories = 205,
            protein = 3.8f,
            carbs = 16.0f,
            fat = 14.2f,
            fiber = 3.5f,
            sugar = 9.8f,
            sodium = 15,
            portionSize = "4 ชิ้น (35g)",
            mealType = "ของว่าง",
            healthTip = "ช็อกโกแลตสวิสแท้โกโก้ 70% อุดมด้วยฟลาโวนอยด์ สารต้านอนุมูลอิสระ และแมกนีเซียม ช่วยคลายความเครียดและบำรุงหลอดเลือดหัวใจ",
            ingredients = listOf("โกโก้แมสสวิส 70%", "เฮเซลนัทคั่วกรอบ", "เนยโกโก้บริสุทธิ์", "น้ำตาลอ้อยธรรมชาติ", "กลิ่นวานิลลาแท้"),
            cuisine = "Swiss"
        )
    )

    val thaiDishes = listOf(
        NutritionAnalysis(
            foodName = "ข้าวมันไก่ต้ม",
            foodNameEn = "Hainanese Chicken Rice",
            calories = 585,
            protein = 28.5f,
            carbs = 72.0f,
            fat = 20.2f,
            fiber = 1.5f,
            sugar = 2.0f,
            sodium = 920,
            portionSize = "1 จาน (350g)",
            mealType = "มื้อเที่ยง",
            healthTip = "โปรตีนสูงจากเนื้อไก่ หากต้องการลดแคลอรี่สามารถเลี่ยงหนังไก่และลดน้ำจิ้มได้",
            ingredients = listOf("ข้าวหุงน้ำซุปไก่", "อก/สะโพกไก่ต้ม", "แตงกวา", "เลือดไก่", "น้ำจิ้มเต้าเจี้ยว", "น้ำซุปฟัก"),
            cuisine = "Thai"
        ),
        NutritionAnalysis(
            foodName = "ผัดกะเพราหมูสับไข่ดาว",
            foodNameEn = "Pad Krapow Pork with Fried Egg",
            calories = 630,
            protein = 32.0f,
            carbs = 65.0f,
            fat = 26.5f,
            fiber = 2.1f,
            sugar = 3.5f,
            sodium = 1150,
            portionSize = "1 จาน (380g)",
            mealType = "มื้อเที่ยง",
            healthTip = "มีสารต้านอนุมูลอิสระจากใบกะเพราและพริก ระวังโซเดียมและน้ำมันจากไข่ดาวทอดกรอบ",
            ingredients = listOf("ข้าวสวยหอมมะลิ", "หมูสับ", "ใบกะเพราสด", "พริกขี้หนูกระเทียม", "ไข่ดาว", "ซอสปรุงรส"),
            cuisine = "Thai"
        ),
        NutritionAnalysis(
            foodName = "ส้มตำไทย + ไก่ย่าง",
            foodNameEn = "Som Tum Thai with Grilled Chicken",
            calories = 380,
            protein = 29.0f,
            carbs = 35.0f,
            fat = 14.0f,
            fiber = 4.8f,
            sugar = 12.0f,
            sodium = 880,
            portionSize = "1 ชุด (320g)",
            mealType = "มื้อเย็น",
            healthTip = "แคลอรี่ต่ำ ใยอาหารสูง วิตามินซีสูงจากมะละกอและมะนาว สดชื่นและดีต่อระบบขับถ่าย",
            ingredients = listOf("มะละกอดิบเส้น", "ถั่วฝักยาว", "มะเขือเทศ", "กุ้งแห้งและถั่วลิสง", "สะโพกไก่ย่างสมุนไพร"),
            cuisine = "Thai"
        ),
        NutritionAnalysis(
            foodName = "ต้มยำกุ้งน้ำใส",
            foodNameEn = "Tom Yum Goong",
            calories = 190,
            protein = 24.0f,
            carbs = 12.0f,
            fat = 4.5f,
            fiber = 3.2f,
            sugar = 3.0f,
            sodium = 960,
            portionSize = "1 ชาม (350ml)",
            mealType = "มื้อเย็น",
            healthTip = "แคลอรี่ต่ำมาก โปรตีนสะอาดจากกุ้ง สมุนไพรข่า ตะไคร้ ใบมะกรูด ช่วยกระตุ้นการเผาผลาญ",
            ingredients = listOf("กุ้งสด", "เห็ดฟาง", "ตะไคร้ ข่า ใบมะกรูด", "พริกขี้หนูสวน", "น้ำมะนาวคั้นสด"),
            cuisine = "Thai"
        ),
        NutritionAnalysis(
            foodName = "สลัดอกไก่อะโวคาโด",
            foodNameEn = "Avocado Chicken Salad",
            calories = 420,
            protein = 35.0f,
            carbs = 18.0f,
            fat = 22.0f,
            fiber = 7.5f,
            sugar = 4.0f,
            sodium = 420,
            portionSize = "1 ชาม (320g)",
            mealType = "มื้อเย็น",
            healthTip = "ไขมันดีสูงจากอะโวคาโด ช่วยบำรุงหัวใจ ใยอาหารสูงมากและโปรตีนลีน เหมาะกับคนรักสุขภาพ",
            ingredients = listOf("อกไก่ย่างฉีก", "อะโวคาโดหั่นเต๋า", "ผักสลัดไฮโดรโปนิกส์", "มะเขือเทศราชินี", "น้ำสลัดบัลซามิก"),
            cuisine = "International"
        ),
        NutritionAnalysis(
            foodName = "โจ๊กหมูใส่ไข่",
            foodNameEn = "Pork Congee with Egg",
            calories = 340,
            protein = 18.0f,
            carbs = 42.0f,
            fat = 11.5f,
            fiber = 1.0f,
            sugar = 1.5f,
            sodium = 790,
            portionSize = "1 ชาม (400g)",
            mealType = "มื้อเช้า",
            healthTip = "ย่อยง่าย สบายท้อง เหมาะสำหรับมื้อเช้า ให้พลังงานต่อเนื่องและอบอุ่นร่างกาย",
            ingredients = listOf("ข้าวต้มบดละเอียด", "หมูสับปั้นก้อน", "ไข่ลวก", "ขิงซอยและต้นหอม", "ซีอิ๊วขาว"),
            cuisine = "Thai"
        )
    )

    // All sample dishes combining Swiss and other popular options
    val sampleDishes = swissDishes + thaiDishes
}
